#!/usr/bin/env python3

from pathlib import Path

import click

ROOT = Path(__file__).resolve().parent.parent.parent
OPTIGA_CERTS_DIR = ROOT / "core/embed/sec/optiga/unix/certs"
SECRET_CERTS_DIR = ROOT / "core/embed/sec/secret/unix/certs"

COMMENT = f"""// This file is auto-generated by `{Path(__file__).relative_to(ROOT)}`.
// Do not edit this file directly. Instead, run `make gen` or `make certs`
// in the root directory."""


def create_array_lines(data: bytes) -> list[str]:
    chunks = [data[i : i + 12] for i in range(0, len(data), 12)]
    return ["    " + ", ".join(f"0x{b:02x}" for b in chunk) + "," for chunk in chunks]


def der_to_header(data: bytes, variable_name: str) -> str:
    lines = [
        COMMENT,
        "",
        f"static const unsigned char {variable_name}[] = {{",
        *create_array_lines(data),
        "};",
        f"static const unsigned int {variable_name}_size = {len(data)};",
    ]

    return "\n".join(lines) + "\n"


def process_cert(
    der_path: Path, header_path: Path, variable_name: str, check: bool
) -> None:
    content = der_to_header(der_path.read_bytes(), variable_name)
    if check:
        if not header_path.exists():
            raise click.ClickException(f"{header_path} is missing")
        if header_path.read_text() != content:
            raise click.ClickException(f"{header_path} is out of date")
    else:
        header_path.write_text(content)
        print(f"Generated {header_path}")


@click.command()
@click.option("--check", is_flag=True)
def generate(check: bool) -> None:
    process_cert(
        OPTIGA_CERTS_DIR / "T2B1.der",
        OPTIGA_CERTS_DIR / "T2B1.h",
        "T2B1_der",
        check,
    )
    process_cert(
        OPTIGA_CERTS_DIR / "T3B1.der",
        OPTIGA_CERTS_DIR / "T3B1.h",
        "T3B1_der",
        check,
    )
    process_cert(
        OPTIGA_CERTS_DIR / "T3T1.der",
        OPTIGA_CERTS_DIR / "T3T1.h",
        "T3T1_der",
        check,
    )
    process_cert(
        OPTIGA_CERTS_DIR / "T3W1.der",
        OPTIGA_CERTS_DIR / "T3W1.h",
        "T3W1_der",
        check,
    )
    process_cert(
        SECRET_CERTS_DIR / "T3W1.der",
        SECRET_CERTS_DIR / "T3W1.h",
        "mcu_device_cert",
        check,
    )

    if check:
        print("All files are up to date.")


if __name__ == "__main__":
    generate()
